version: '3.4'

services:
  awssign2:
    image: awssign2
    build:
      context: node_modules/less/node_modules/aws-sign2
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 42305:42305
