version: '3.4'

services:
  awssign2:
    image: awssign2
    build:
      context: node_modules/less/node_modules/aws-sign2
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 42305:42305
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
